### ISSUE TITLE
no dd() function

### ISSUE THREAD

**Issue by mattpramschufer** [moazam1/yoast-seo-cleaner#1]
I haven't personally ran your code yet, but browsing through I saw you have 

```	public function ysc_cleanup_admin_action() {
		$this->do_cleanup();
		dd(get_option('activate_yoast_seo_cron_job'));
		wp_redirect( $_SERVER['HTTP_REFERER'] . '&updated=1');
		exit();
	}
```

I don't think you declared an actual `dd` function.  I know that is a default Laravel function but not in WP.  :)

**Comment by moazam1** [comment]
@mattpramschufer Nice catch! I have pushed update.
